import Link from "next/link";
import PublicHeader from "@/components/PublicHeader";

const localSteps = [
  ["Install Node.js", "Install the current Node.js LTS version on the computer that will run the server. Restart PowerShell after installation.", "node --version\nnpm --version"],
  ["Open the project", "Copy the petshop-next folder to the other computer, then open PowerShell inside that folder.", "cd C:\\path\\to\\Petshop\\petshop-next"],
  ["Install packages", "Download the Next.js, React, and TypeScript packages defined by this project.", "npm install"],
  ["Prepare environment settings", "Copy .env.example to .env.local. Replace every example value with your hosted database, authentication, and email credentials.", "Copy-Item .env.example .env.local"],
  ["Start on your local network", "The hostname option allows phones and computers on the same Wi-Fi network to open the application.", "npm run dev -- --hostname 0.0.0.0"],
  ["Find the server address", "Run ipconfig and find the Wi-Fi adapter's IPv4 Address, for example 192.168.1.25.", "ipconfig"],
  ["Open it from another device", "Keep the server computer running. Connect the second device to the same Wi-Fi and open the address below in its browser.", "http://192.168.1.25:3000"],
  ["Allow Windows Firewall if asked", "Approve private-network access for Node.js. If the page is blocked, allow inbound TCP port 3000 on private networks.", "Windows Security → Firewall → Allow an app"],
] as const;

export default function HowToRun() {
  return <><PublicHeader /><main className="guidePage"><div className="guideWrap"><section className="guideHero"><span className="eyebrow">System operations note</span><h1>How to Run This</h1><p>A step-by-step tutorial for starting Dizon&apos;s Petshop on this computer or another device connected to your local network.</p><div className="guideNote"><b>Important:</b> This Next.js folder is separate from the older XAMPP/PHP version. Install Node.js before using these commands.</div></section><section className="guideSection"><h2>Run the development server</h2><div className="stepList">{localSteps.map(([title,description,command],index)=><article className="guideStep" key={title}><span>{index+1}</span><div><h3>{title}</h3><p>{description}</p><pre className="code">{command}</pre></div></article>)}</div></section><section className="guideSection"><h2>Run a production build locally</h2><div className="guideStep"><span>1</span><div><h3>Build and start</h3><p>Use this after development testing. It checks the application and starts the optimized production server.</p><pre className="code">npm run build{`\n`}npm run start -- --hostname 0.0.0.0</pre></div></div></section><section className="guideSection"><h2>Deploy to Vercel</h2><div className="stepList"><article className="guideStep"><span>1</span><div><h3>Push petshop-next to GitHub</h3><p>Create a repository and commit this folder. Never commit .env.local.</p></div></article><article className="guideStep"><span>2</span><div><h3>Import the repository in Vercel</h3><p>Vercel detects Next.js automatically. Add the environment variables from .env.example under Project Settings.</p></div></article><article className="guideStep"><span>3</span><div><h3>Deploy and test</h3><p>Open the generated HTTPS URL and test authentication, email, database access, and reservations.</p></div></article></div><div className="guideLinks"><Link className="primaryButton" href="/">Return Home</Link><Link className="outlineButton" href="/client/register">Create Account</Link></div></section></div></main></>;
}
