import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import AdminSidebar from "@/components/AdminSidebar";
import { prisma } from "@/lib/prisma";
import { readSessionToken, sessionCookieName } from "@/lib/session";
import { createProduct, updateAddon, updateClientStatus, updateGroomingStatus, updatePackage, updateProduct, updateProductReservationStatus } from "../actions";

const money = (value: { toString(): string }) => Number(value.toString()).toFixed(2);
const date = (value: Date) => new Intl.DateTimeFormat("en-PH", { month:"short",day:"2-digit",year:"numeric" }).format(value);

export default async function AdminDashboard() {
  const cookieStore = await cookies();
  const session = await readSessionToken(cookieStore.get(sessionCookieName)?.value);
  if (session?.role !== "Admin") redirect("/admin/login");
  const currentAdmin = await prisma.user.findFirst({
    where: { id: session.userId, role: "Admin", accountStatus: "Active" },
    select: { id: true },
  });
  if (!currentAdmin) redirect("/admin/login");

  const [clients, products, packages, addons, appointments, productReservations] = await Promise.all([
    prisma.user.findMany({where:{role:{not:"Admin"}},orderBy:{createdAt:"desc"}}),
    prisma.product.findMany({orderBy:[{isActive:"desc"},{category:"asc"},{productName:"asc"}]}),
    prisma.styleSizePricing.findMany({include:{style:true},orderBy:[{styleId:"asc"},{pricingId:"asc"}]}),
    prisma.groomingAddon.findMany({orderBy:{addonName:"asc"}}),
    prisma.groomingAppointment.findMany({include:{customer:true,pet:true,style:true,groomer:true},orderBy:[{appointmentDate:"desc"},{appointmentTime:"desc"}],take:100}),
    prisma.productReservation.findMany({include:{customer:true,items:{include:{product:true}}},orderBy:{createdAt:"desc"},take:30}),
  ]);
  const lowStock = products.filter(item=>item.isActive&&item.stockQuantity<=item.reorderLevel).length;
  const activeAppointments = appointments.filter(item=>item.status==="Pending"||item.status==="Confirmed").length;
  const productSales = new Map<string, number>();
  for (const reservation of productReservations.filter(item => item.status !== "Cancelled")) for (const item of reservation.items) productSales.set(item.product.productName, (productSales.get(item.product.productName) || 0) + item.quantity);
  const topProducts = [...productSales].sort((a,b)=>b[1]-a[1]).slice(0,10);
  const appointmentStats = ["Pending","Confirmed","Completed","Cancelled"].map(status => [status, appointments.filter(item => item.status === status).length] as const);
  const groomerStats = [...new Set(appointments.map(item => item.groomer.groomerName))].map(name => [name, appointments.filter(item => item.groomer.groomerName === name).length] as const);
  const maxProductSales = Math.max(1, ...topProducts.map(([,value]) => value));
  const maxAppointments = Math.max(1, ...appointmentStats.map(([,value]) => value), ...groomerStats.map(([,value]) => value));

  return <main className="dashShell adminDash"><AdminSidebar /><section className="dashContent"><header className="dashTop"><div><small>ADMIN CENTER</small><b>Welcome, {session.name}</b></div><form action="/api/auth/logout" method="post"><button className="logoutButton">Secure logout</button></form></header>

    <section className="dashHero" id="overview"><small>LIVE DATABASE OVERVIEW</small><h1>Good operations start here.</h1><p>Every figure and management control below is connected to the configured PostgreSQL database.</p></section>
    <section className="metricGrid"><article className="metric"><span>Client accounts</span><strong>{clients.length}</strong><small>Verified system users</small></article><article className="metric"><span>Active products</span><strong>{products.filter(item=>item.isActive).length}</strong><small>Across catalog groups</small></article><article className="metric"><span>Low-stock items</span><strong>{lowStock}</strong><small>At or below alert level</small></article><article className="metric"><span>Active bookings</span><strong>{activeAppointments}</strong><small>Pending or confirmed</small></article></section>
    <section className="adminDataSection" id="clients"><div className="dataHeading"><div><small>CLIENT MANAGEMENT</small><h2>Accounts and access</h2></div><span>{clients.length} clients</span></div><div className="dataTableWrap"><table className="adminTable"><thead><tr><th>Client</th><th>Contact</th><th>Joined</th><th>Account access</th></tr></thead><tbody>{clients.map(client=><tr key={client.id}><td><b>{[client.firstName,client.surname].filter(Boolean).join(" ")||"Customer"}</b><small>{client.email}</small></td><td>{client.phoneNumber||"Not provided"}</td><td>{date(client.createdAt)}</td><td><form action={updateClientStatus} className="databaseForm inline"><input type="hidden" name="id" value={client.id}/><select name="status" defaultValue={client.accountStatus}><option>Active</option><option>Suspended</option></select><button>Update</button></form></td></tr>)}</tbody></table></div></section>

    <section className="adminDataSection" id="inventory"><div className="dataHeading"><div><small>INVENTORY MANAGEMENT</small><h2>Products and quantity</h2></div><span>{products.length} records</span></div><details className="createPanel"><summary>＋ Add a new product</summary><form action={createProduct} className="databaseForm productEditGrid"><input name="sku" placeholder="SKU" required/><input name="name" placeholder="Product name" required/><input name="category" placeholder="Category" required/><select name="group"><option>Food</option><option>Shampoo</option><option>Other</option></select><input name="price" type="number" min="0" step="0.01" placeholder="Price" required/><input name="stock" type="number" min="0" placeholder="Quantity" required/><input name="reorder" type="number" min="0" defaultValue="5" placeholder="Alert level" required/><input name="description" placeholder="Description"/><button>Add Product</button></form></details><div className="databaseCardGrid">{products.map(product=><form action={updateProduct} className="databaseCard" key={product.productId}><input type="hidden" name="id" value={product.productId}/><div className="databaseCardTop"><small>{product.sku||`PRODUCT-${product.productId}`}</small><span className={product.stockQuantity<=product.reorderLevel?"stockLow":"stockGood"}>{product.stockQuantity<=product.reorderLevel?"Low stock":"In stock"}</span></div><input name="name" defaultValue={product.productName} aria-label="Product name"/><input name="category" defaultValue={product.category} aria-label="Category"/><div className="productEditGrid"><select name="group" defaultValue={product.productGroup}><option>Food</option><option>Shampoo</option><option>Other</option></select><input name="price" type="number" min="0" step="0.01" defaultValue={money(product.price)} aria-label="Price"/><input name="stock" type="number" min="0" defaultValue={product.stockQuantity} aria-label="Quantity"/><input name="reorder" type="number" min="0" defaultValue={product.reorderLevel} aria-label="Alert level"/></div><div className="databaseCardFooter"><label><input type="checkbox" name="active" defaultChecked={product.isActive}/> Visible</label><button>Save Product</button></div></form>)}</div></section>

    <section className="adminDataSection" id="packages"><div className="dataHeading"><div><small>GROOMING CATALOG</small><h2>Packages and prices</h2></div><span>{packages.length+addons.length} price records</span></div><div className="managementColumns"><div className="dataTableWrap"><h3>Size-based packages</h3><table className="adminTable"><thead><tr><th>Package</th><th>Pet size</th><th>Price</th><th></th></tr></thead><tbody>{packages.map(item=><tr key={item.pricingId}><td colSpan={4}><form action={updatePackage} className="databaseForm packageRow"><input type="hidden" name="id" value={item.pricingId}/><input name="name" defaultValue={item.style.styleName}/><span>{item.petSize}</span><input type="number" name="price" step="0.01" min="0" defaultValue={money(item.price)}/><button>Save</button></form></td></tr>)}</tbody></table></div><div className="dataTableWrap"><h3>Add-on services</h3><div className="addonList">{addons.map(item=><form action={updateAddon} className="databaseForm packageRow" key={item.addonId}><input type="hidden" name="id" value={item.addonId}/><input name="name" defaultValue={item.addonName}/><input type="number" name="price" step="0.01" min="0" defaultValue={money(item.price)}/><button>Save</button></form>)}</div></div></div></section>

    <section className="adminDataSection" id="reservations"><div className="dataHeading"><div><small>OPERATIONS</small><h2>Reservation management</h2></div><span>Live status controls</span></div><div className="dataTableWrap"><h3>Grooming appointments</h3><table className="adminTable"><thead><tr><th>Reference</th><th>Client / Pet</th><th>Date</th><th>Status</th></tr></thead><tbody>{appointments.map(item=><tr key={item.appointmentId.toString()}><td><b>{item.reservationCode}</b><small>{item.style.styleName}</small></td><td>{item.customer.customerName}<small>{item.pet.petName}</small></td><td>{date(item.appointmentDate)}</td><td><form action={updateGroomingStatus} className="databaseForm inline"><input type="hidden" name="id" value={item.appointmentId.toString()}/><select name="status" defaultValue={item.status}><option>Pending</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select><button>Save</button></form></td></tr>)}</tbody></table></div><div className="dataTableWrap spaced"><h3>Product pickup reservations</h3><table className="adminTable"><thead><tr><th>Reference</th><th>Client / Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{productReservations.map(item=><tr key={item.reservationId.toString()}><td><b>{item.reservationCode}</b><small>{date(item.createdAt)}</small></td><td>{item.customer.customerName}<small>{item.items.map(line=>`${line.product.productName} × ${line.quantity}`).join(", ")}</small></td><td>PHP {money(item.totalAmount)}</td><td>{item.status==="Cancelled"?<span className="statusChip">Cancelled</span>:<form action={updateProductReservationStatus} className="databaseForm inline"><input type="hidden" name="id" value={item.reservationId.toString()}/><select name="status" defaultValue={item.status}><option value="Pending">Pending</option><option value="Confirmed">Confirmed</option><option value="Ready for Pickup">Ready for Pickup</option><option value="Claimed">Claimed</option><option value="Cancelled">Cancelled</option></select><button>Save</button></form>}</td></tr>)}</tbody></table></div></section>
    <section className="adminDataSection" id="reports"><div className="dataHeading"><div><small>BUSINESS REPORTS</small><h2>Sales and appointment insights</h2></div><span>Latest 100 records</span></div><div className="reportGrid"><ReportChart title="Top-selling products" rows={topProducts} maximum={maxProductSales} empty="No product sales yet."/><ReportChart title="Appointment transactions" rows={appointmentStats} maximum={maxAppointments}/><ReportChart title="Groomer workload" rows={groomerStats} maximum={maxAppointments} empty="No groomer activity yet."/></div></section>
  </section></main>;
}

function ReportChart({ title, rows, maximum, empty = "No report data yet." }: { title: string; rows: readonly (readonly [string,number])[]; maximum: number; empty?: string }) {
  return <article className="reportCard"><h3>{title}</h3>{rows.length ? <div className="reportBars">{rows.map(([label,value]) => <div key={label}><header><span>{label}</span><b>{value}</b></header><i><em style={{width:`${Math.max(value ? 6 : 0,(value/maximum)*100)}%`}}/></i></div>)}</div> : <p>{empty}</p>}</article>;
}
